### ISSUE TITLE
Netrunner Desktop Checklist

### ISSUE THREAD

**Issue by star-buck** [blue-systems/netrunner-releases#196]
== BASIC TESTS ==

* base test
* [ ] all programs there? see below for program list
* [ ] installation works
* [ ] german install works
* [ ] uefi install works
* [ ] logout/login works after second boot
* [ ] tty1 - tty7 ALT+STRG+F1 - F7

----

* plasma:
* [ ] meta key works to invoke menu
* [ ] menu sorted alphabetic, that is the categories and the menu entrie
* [ ] drag windows from titlebar

----

* programs:
* [ ] firefox loads
* [ ] thunderbird loads
* [ ] steam loads

----

* [ ] synaptic: repo list correct?
* [ ] synaptic: refresh works after uncommenting "testing"
* [ ] dolphin: updating all packages after testing was added works

----

* firefox:
* [ ] ublock works?
* [ ] downloading google logo works?
* [ ] rt.com flash works?
* [ ] magnet torrent works? https://www.limetorrents.cc/Introducing-UNIX-and-Linux-(Grassroots)-by-Mike-Joy--True-PDF--torrent-8660949.html

-------------------------
== PROGRAMS in Menu ==

games 10:
* burgerspace
* chess (gnome-chess) [is chessengine working after making first move?]
* frozen bubble
* gltron
* gnome-sudoku/gnudoq
* kbreakout
* kmahjongg
* kmines
* ksnakeduel
* steam [works?]

----

graphics 5:
* gimp
* gwenview
* inkscape
* krita
* skanlite (/simplescan)

----

internet 6:
* firefox
* kde marble [search for street works, e.g. Abbot Kinney?] 
* pidgin
* qttransmission [clicking on a magnet link in ff works?]
* skype
* thunderbird
--
* (x11vncserver) should only be in core? -> move to: Settings
(steam hidden)

----

multimedia 8:
* audacious
* gmusicbrowser
* handbrake
* kamoso (/cheese)
* kdenlive
* pulseaudio volume control
* smplayer (vlc)
* yarock
--
* vokoscreen (should move to Utilities), simplescreenrecorder
* (mpv hidden)

----

office 4:
* LO suite
* calc
* impress
* writer
--
* okular (should go to utilities)
* (LO math hidden)
* (LO draw hidden)
* (LO Base hidden)
* (Kmail hidden)

----

settings 5:
* grub customizer
* kvantum manager
* print settings
* system settings
* X11VNC Server

----

system 11 + 1:
* temp. removed, needs to be back: windows wireless (ndisgtk)
--
* (calamares) , removed after install
* discover
* dolphin
* info center
* kde partition manager
* konsole
* ksysguard
* kwallet manager
* network drives
* synaptic package manager (or octopi in rolling)
* update manager
* yakuake
--
* hidden: virtualbox (/qemu) should move to Utilities

----

utilities 8:
* ark
* isowriter (/suse imagwriter or isoimagewriter/-neon)
* kate
* kcalc
* okular
* spectacle
* virtualbox (/qemu)
* vokoscreen (simplescreenrecorder?)

--
* hidden: kvantum manager

----

web 4:
* Hooktube
* Skype-Web
* Telegram
* Whatsapp
